# Google Cloud App Engine Configuration
runtime: nodejs20

# Instance configuration
instance_class: F2
automatic_scaling:
  min_instances: 1
  max_instances: 5
  cpu_utilization:
    target_utilization: 0.65

# Environment variables (will be set in GCP Console)
env_variables:
  NODE_ENV: production
  PORT: 8080

# Health check
health_check:
  enable_health_check: True
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

# Static files handling
handlers:
  # Serve frontend static files
  - url: /css
    static_dir: frontend/css
    secure: always
    
  - url: /js
    static_dir: frontend/js
    secure: always
    
  - url: /images
    static_dir: frontend/images
    secure: always
    
  # API routes - serve with Node.js
  - url: /api/.*
    script: auto
    secure: always
    
  # Main application (SPA) - serve index.html for all other routes
  - url: /.*
    static_files: frontend/index.html
    upload: frontend/index.html
    secure: always

# Resources
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Deployment settings
deploy:
  timeout: 300
