# Google Cloud App Engine Configuration
runtime: nodejs20

# Instance configuration
instance_class: F2
automatic_scaling:
  min_instances: 1
  max_instances: 5
  cpu_utilization:
    target_utilization: 0.65

# Environment variables
env_variables:
  NODE_ENV: production
  PORT: 8080
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_NAME: ${DB_NAME}
  JWT_SECRET: ${JWT_SECRET}
  JWT_EXPIRES_IN: 7d
  FRONTEND_URL: ${FRONTEND_URL}

# Health check
health_check:
  enable_health_check: True
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

# Network settings
network:
  forwarded_ports: 80, 443

# Static files handling
handlers:
  # Serve frontend static files
  - url: /css
    static_dir: frontend/css
    secure: always
    
  - url: /js
    static_dir: frontend/js
    secure: always
    
  - url: /images
    static_dir: frontend/images
    secure: always
    
  # API routes
  - url: /api/.*
    script: auto
    secure: always
    
  # Main application (SPA)
  - url: /.*
    static_files: frontend/index.html
    upload: frontend/index.html
    secure: always

# Resources
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Deployment settings
deploy:
  timeout: 300

# Beta features (if needed)
# beta_settings:
#   cloud_sql_instances: your-project:region:your-instance
