# Google Cloud Build Configuration
steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    
  # Build the application
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    
  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

# Configure the build
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Substitute environment variables
substitutions:
  _NODE_ENV: 'production'

# Timeout
timeout: '1200s'
